
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Allocation
{

    public int ca_id { get; set; }

    public string day { get; set; }

    public string start_time { get; set; }

    public string end_time { get; set; }

    public string t_id { get; set; }

    public string class_id { get; set; }

    public string sub_id { get; set; }

    public string no_of_students { get; set; }

}

}
