//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {

        [Required]
        public int billId { get; set; }

        [Required]
        [StringLength(55, MinimumLength =3)]
        public string type { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public System.DateTime date { get; set; }

        [Required]
        [DataType(DataType.Currency)]
        public double amount { get; set; }

        [StringLength(40, MinimumLength =0)]
        public string description { get; set; }
    }
}
