
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class classroom
{

    public int class_id { get; set; }

    public Nullable<int> max { get; set; }

    public Nullable<int> min { get; set; }

    public string location { get; set; }

    public string name { get; set; }

    public string ac_nonac { get; set; }

}

}
