
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public employee()
    {

        this.emp_attendence = new HashSet<emp_attendence>();

    }


    public int emp_id { get; set; }

    public string full_name { get; set; }

    public Nullable<double> salary { get; set; }

    public Nullable<System.DateTime> birthday { get; set; }

    public string email { get; set; }

    public string contact_num { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<emp_attendence> emp_attendence { get; set; }

}

}
