//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class lab
    {
        [Required(ErrorMessage = "The field Lab Number, Reqiured")]
        [Range(1, 10, ErrorMessage = "The field Lab Number must be between 1 and 10.")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Please Enter Valid Positive Number.Only Numbers Are Acceptable.")]
        public int LabNo { get; set; }
        [Required(ErrorMessage = "The field Floor, Reqiured")]
        [Range(1, 10, ErrorMessage = "The field Floor Number must be between 1 and 10.")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Please Enter Valid Positive Number.Only Numbers Are Acceptable.")]
        public int floor { get; set; }
    }
}
