//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class lab
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Provide Lab Number")]
        public int LabNo { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please Provide Floor Number")]
        public int floor { get; set; }
    }
}
