//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class notify
    {
        public int n_id { get; set; }

        [Required(ErrorMessage = "Required")]
        public string title { get; set; }

        [Required(ErrorMessage = "Required")]
        public string descript { get; set; }
    }
}
