
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Student
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Student()
    {

        this.student_tute = new HashSet<student_tute>();

        this.subjects = new HashSet<subject>();

        this.marksInfoes = new HashSet<marksInfo>();

    }


    public int Id { get; set; }

    public string Full_Name { get; set; }

    public string School { get; set; }

    public string Address { get; set; }

    public string Division { get; set; }

    public string Email { get; set; }

    public string Contact_No { get; set; }

    public string Parent_Name { get; set; }

    public string Parent_Mobile { get; set; }

    public string Parent_Work { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<student_tute> student_tute { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<subject> subjects { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<marksInfo> marksInfoes { get; set; }

}

}
