//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teacher()
        {
            this.tutes = new HashSet<tute>();
        }
    
        public int t_id { get; set; }

        [Required(ErrorMessage = "Required")]
        public string full_name { get; set; }

        [Required(ErrorMessage = "Required")]
        public string school { get; set; }

        [Required(ErrorMessage = "Required")]
        public string division { get; set; }

        [Required(ErrorMessage = "Required")]
        public string t_address { get; set; }

        [Required(ErrorMessage = "Required")]
        public string contact_number { get; set; }

        [Required(ErrorMessage = "Required")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                           @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                           @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                           ErrorMessage = "Email is not valid")]
        public string email { get; set; }

        public Nullable<int> fees { get; set; }
        public Nullable<int> noStudents { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tute> tutes { get; set; }
    }
}
