
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StudentApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tutes
{

    public int Tute_id { get; set; }

    public string Tute_title { get; set; }

    public string Sub_name { get; set; }

    public string Teacher_name_ { get; set; }

}

}
