//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int UserId_ { get; set; }
        [Required(ErrorMessage = "Required")]
        public string UserName_ { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Password_ { get; set; }
        public bool IsActive_ { get; set; }
    }
}
